Title = "AnyTime (Extended Mix)"
Album = "SPRS031"
Artist = "Don Diablo"
Genre = "Future House"
ReleaseDate = "2018-08-04"
Label = "Spinnin' Records (SPRS)"
Country = "Netherlands"
VideoLink = "https://youtu.be/qzNQLKgaLi0"
DurationInSeconds = 274
DurationInMinutes = 4.57
